### ISSUE TITLE
컨퍼런스 행사일 결정

### ISSUE THREAD

**Issue by mrchypark** [R-Korea/RUCK2020#1]
주말 vs 주중

10월, 11월, 12월

을 고려해서 정하면 좋을 것 같습니다.

제 후보일은 11월 28일 입니다.

**Comment by mrchypark** [comment]
제 선택은 11월, 주말입니다. 12월은 오히려 다른 일들 때문에 발표자 모집이 어려워 지지 않을까 생각이 들었구요. 그래서 11월을 생각하였습니다. 주말, 주중은 특별히 선호하지는 않습니다만, 아직 송출 방식을 결정하지 않은 상황이라, 전형적으로 주말로 선택했습니다.

**Comment by loveactualry** [comment]
저는 11월 주말입니다. 준비 기간을 고려하면 28일이 좋지 않을까 생각합니다!

**Comment by mrchypark** [comment]
투표는 [합의](https://github.com/R-Korea/RUCK2020/blob/master/proposals/governance/consensus.md) 방식 중 게으른 합의로 진행하겠습니다.

투표는 아래 아이콘으로 진행하겠습니다.
+1 : 업보트    
+0 : 웃는 표정    
-0 : 심통난 표정    
-1 : 다운보트    

![image](https://user-images.githubusercontent.com/6179259/94760723-46c6f880-03de-11eb-91af-95093634f646.png)

**Comment by mrchypark** [comment]
11월 28일 투표장 입니다.

**Comment by r-kor** [comment]
@mrchypark  전체 to do list를 한 번 정리하시는 건 어떨까요?

**Comment by mrchypark** [comment]
@r-kor 따로 이슈 생성해주시면 감사하겠습니다.

**Comment by mrchypark** [comment]
운영위 +1 4표와 커뮤니티 +1 6표로 컨퍼런스 행사일으느 11월 28일로 정하겠습니다.

투표에 참여해주신 모든 분들께 감사드립니다.

**Comment by mrchypark** [comment]
투표에 참여해주신 분들 대단히 감사합니다. 이런 커뮤니티 기여를 통해 일이 하나하나 진행되는 것 같습니다.

@pherephobia
@jnhyeon
@wonseongkim
@sychanmul
@Heterovol
@ferti1969

투표에 참여해주신 운영진 분들도 감사드립니다. 이슈 닫도록 하겠습니다.
@KeunhoLee
@youngwoos
@loveactualry
