### ISSUE TITLE
발표자 단톡방 개설 및 관리자

### ISSUE THREAD

**Issue by mrchypark** [R-Korea/RUCK2020#15]
https://github.com/R-Korea/RUCK2020/issues/6

위 이슈로 발표자 및 발표자 후보 추천 및 발표자분들에게 공지 할 수 있는 단톡방을 개설하고자 합니다.

이에 따라 관리자를 선정해야 합니다.

2가지 방식이 가능해 보여 이슈 작성합니다.

1. 현 운영위 내에서 자원
1. 커뮤니티에 자원 요청

**Comment by youngwoos** [comment]
1에 찬성합니다.

**Comment by mrchypark** [comment]
운영위 자원 투표장

**Comment by mrchypark** [comment]
커뮤니티 자원 요청 투표장

**Comment by mrchypark** [comment]
혹시 운영위 자원이라면, 자원하실 분도 댓글로 알려주세요.

**Comment by loveactualry** [comment]
단톡방 운영 자원합니다.

**Comment by mrchypark** [comment]
운영 자원 해주신 분께 투표 부탁드려요.

**Comment by jhgil92** [comment]
단톡방 운영 적극 지원하겠습니다.

**Comment by mrchypark** [comment]
투표 상 @loveactualry 님이 생성해주시면 감사하겠습니다.

오픈 채팅방을 생성하시고, 여기 링크 공유 해주세요.

커뮤니티에 홍보 해주시는 것도 부탁드리겠습니다.

자원해주셔서 감사합니다.

**Comment by loveactualry** [comment]
넵, 알겠습니다.

발표자 지원 및 발표자 후보 추천방을 주제로 생성하도록 하겠습니다.

일정이 촉박하지만 세부사항(방식, 마감일 등등)이 대략적으로 윤곽이 잡혀야 생성하고 발표 지원자 분들에게 안내드리는데 도움이 될 것 같습니다.

@jhgil92 님께서 카톡방 운영에 같이 도움 주셔도 좋을 것 같다는 의견 드립니다.

**Comment by jhgil92** [comment]
> 넵, 알겠습니다.
> 
> 발표자 지원 및 발표자 후보 추천방을 주제로 생성하도록 하겠습니다.
> 
> 일정이 촉박하지만 세부사항(방식, 마감일 등등)이 대략적으로 윤곽이 잡혀야 생성하고 발표 지원자 분들에게 안내드리는데 도움이 될 것 같습니다.
> 
> @jhgil92 님께서 카톡방 운영에 같이 도움 주셔도 좋을 것 같다는 의견 드립니다.

홍보/공지 등 적극적으로 돕겠습니다. (카톡 아이디 : godco92)

**Comment by loveactualry** [comment]
> > 넵, 알겠습니다.
> > 발표자 지원 및 발표자 후보 추천방을 주제로 생성하도록 하겠습니다.
> > 일정이 촉박하지만 세부사항(방식, 마감일 등등)이 대략적으로 윤곽이 잡혀야 생성하고 발표 지원자 분들에게 안내드리는데 도움이 될 것 같습니다.
> > @jhgil92 님께서 카톡방 운영에 같이 도움 주셔도 좋을 것 같다는 의견 드립니다.
> 
> 홍보/공지 등 적극적으로 돕겠습니다. (카톡 아이디 : godco92)

넵넵. 연락 드리겠습니다. 내용 논의가 필요할 것 같습니다!

**Comment by loveactualry** [comment]
안녕하세요. 커뮤니티에 발표자 모집을 알릴 양식을 만들어봤습니다.
아직 트랙이 확정되지 않아 두가지 버전으로 만들었습니다.
주제 없이 공지하면 지원자분들께서도 막연하지 않을까 하는 걱정에..... ㅠ
**_전면적으로 뒤엎어도 되니 많은 의견 부탁드립니다._**

트랙 미확정인 경우 / 트랙 확정인 경우

- 1. 트랙 미확정인 경우

> 안녕하세요, RUCK(커뮤니티 혹은 단체 이름).
> 
> 올해도 어김없이 RUCK를 개최합니다. 올해 RUCK는 참여와 발굴이라는 비전을 갖고 최초로 온라인으로 진행합니다.
> 온라인으로 개최하는 만큼 다양한 분야에서 많은 분을 모시고 컨퍼런스를 진행하려고 합니다.
> 
> 현재 확실한 주제가 정해진 것은 없으나 발표자 지원 혹은 추천을 받고 있습니다.
> 
> 아래 오픈 카카오톡방에서 많은 지원과 의견 부탁드립니다!
> https://open.kakao.com/o/ggWBTzBc

- 2. 트랙 확정인 경우

> 안녕하세요, RUCK(커뮤니티 혹은 단체 이름).
> 
> 올해도 어김없이 RUCK를 개최합니다. 올해 RUCK는 참여와 발굴이라는 비전을 갖고 최초로 온라인으로 진행합니다.
> 온라인으로 개최하는 만큼 다양한 분야에서 많은 분을 모시고 컨퍼런스를 진행하려고 합니다.
> 
> 올해 RUCK 트랙은 다음과 같습니다.
> 
> - 트랙
> - 트랙
> 
> 발표 모집 일정(예시)
> 발표 모집 1차 마감: 10월 24일
> 발표 모집 2차 마감: 10월 31일
> 발표 확정 및 안내: 발표 접수 확인 후, 상시 안내 or 날짜
> 
> 카카오톡 오픈 채팅방에서 지원 혹은 추천 부탁드립니다.
> 
> 오픈 채팅방
> 
> https://open.kakao.com/o/ggWBTzBc

**Comment by mrchypark** [comment]
@loveactualry 우선 트랙에 대해서 계속 논의중이라 변경될 수 있다 고 하고 진행하면 어떨까요?

이 체널은 발표자를 위한 채널이기도 하겠지만, 발표자 발굴을 위한 채널이 될 수 도 있을 것 같습니다.

**Comment by loveactualry** [comment]
> @loveactualry 우선 트랙에 대해서 계속 논의중이라 변경될 수 있다 고 하고 진행하면 어떨까요?
> 
> 이 체널은 발표자를 위한 채널이기도 하겠지만, 발표자 발굴을 위한 채널이 될 수 도 있을 것 같습니다.

넵, 알겠습니다. 완벽하지 않더라도 홍보를 먼저 진행해야 겠네요!!
문구 수정해서 다시 공유하도록 하겠습니다!

**Comment by mrchypark** [comment]
@loveactualry 넵 개설하고 url 공유해주시면 이번 발표 제안자 분께도 공유드리겠습니다.

링크를 코멘트로 공유해주시면 이슈 닫고, README 업데이트 하겠습니다.

**Comment by loveactualry** [comment]
> [RUCK 2020 발표자 지원 및 후보 추천] 
> 
> 안녕하세요, RUCK(커뮤니티 혹은 단체 이름).
> 
> 올해도 어김없이 RUCK를 개최합니다. 개최일은 11월 28일 토요일입니다!
> 올해 RUCK는 참여와 발굴이라는 비전을 갖고 최초로 온라인으로 진행합니다.
> 온라인으로 개최하는 만큼 다양한 분야에서 많은 분을 모시고 컨퍼런스를 진행하려고 합니다.
> 
> 참여와 발굴이라는 비전으로 발표 지원자와 추천을 우선 지원 받고자 합니다.
> 
> 현재 운영진 내부에서 발표 트랙에 대해 논의중이며 추후 확정할 예정입니다.
> 
> 아래 오픈 카카오톡방에서 많은 지원과 의견 부탁드립니다!
> https://open.kakao.com/o/ggWBTzBc

@jhgil92  내용 검토 부탁 드려도 괜찮을까요? 추가 혹은 수정할 부문 있으면 말씀 부탁드립니다!

**Comment by jhgil92** [comment]
> > [RUCK 2020 발표자 지원 및 후보 추천]
> > 안녕하세요, RUCK(커뮤니티 혹은 단체 이름).
> > 올해도 어김없이 RUCK를 개최합니다. 개최일은 11월 28일 토요일입니다!
> > 올해 RUCK는 참여와 발굴이라는 비전을 갖고 최초로 온라인으로 진행합니다.
> > 온라인으로 개최하는 만큼 다양한 분야에서 많은 분을 모시고 컨퍼런스를 진행하려고 합니다.
> > 참여와 발굴이라는 비전으로 발표 지원자와 추천을 우선 지원 받고자 합니다.
> > 현재 운영진 내부에서 발표 트랙에 대해 논의중이며 추후 확정할 예정입니다.
> > 아래 오픈 카카오톡방에서 많은 지원과 의견 부탁드립니다!
> > https://open.kakao.com/o/ggWBTzBc
> 
> @jhgil92 내용 검토 부탁 드려도 괜찮을까요? 추가 혹은 수정할 부문 있으면 말씀 부탁드립니다!

@loveactualry 내용에 대한 별도 이견 없습니다! 내일 회의에서 해당 내용 공유해서 배포 계획 수립하면 어떨까요?

**Comment by loveactualry** [comment]
음... 제가 회의하면서 같이 카톡방 링크 공유를 진행하고 있었습니다. 페이지 게시 관련 논의가 진행되면 추가적으로 커뮤니티 게시 진행을 하도록 하겠습니다! Close 해주셔도 될 것 같습니다.
