### ISSUE TITLE
발표 방식과 발표자 모집 방법

### ISSUE THREAD

**Issue by mrchypark** [R-Korea/RUCK2020#17]
많은 사람들이 참여하는 RUCK2020이 되기 위해서, 발표 모집 방법에 대한 논의가 필요합니다.

발표 방식은 사전 녹화후 송출 및 동시간대 발표자의 채팅(혹은 댓글)으로의 질의응답 을 제안합니다.

제가 제안하는 방식은 아래와 같습니다.

1. 트랙과 시간을 정합니다. (예 3개 트랙, 발표당 20분)  << 이 부분에 의견 부탁드립니다. 트랙을 정하는 방식에 있어 다른 대안이 있기를 바라고 있습니다.
1. 스케줄표를 공개하고, 발표자가 선점하게 합니다.
1. 선점 방식은 녹화된 영상 업로드입니다.
1. 사전에 공유한 체크리스트로 검수하여 p/f 만 결정합니다.
1. 체크리스트의 검수를 위하여 검수인단을 모집합니다.

발표 후보자에게 체크리스트와 pass/fail 기준을 공유합니다.
검수인단의 체크 이후 pass 는 선점 성공, fail시 리스트에서 제거됩니다.

체크리스트는 최소한의 품질 확인을 위한 내용으로 구성할 예정입니다.
아래는 예시입니다.

1. 영상, 음성 품질(노이즈 여부)
1. 제목과 내용 일치 여부
1. 행동 강령 위반 여부
1. 발표 능력 1-5, 장표 만듬세 1-5 (더해서 3 이상)

검수인단의 합의 승인으로 p/f 을 정하면 좋을 것 같습니다.

많은 부분을 동시에 토론해야 해서, 제가 생각하는 발표 형태와 발표자 모집 형태를 공유드렸습니다.

**Comment by loveactualry** [comment]
- 트랙 관련해서는 운영진 내부에서 논의가 필요한거죠?
- 검수 후, fail이 될 경우 발표자 내용 보완 후 pass가 될 가능성이 있는건지요?
- 운영진 내에서 발표자 녹화 지원 논의(장비, 장소 등등)가 필요할 거라 생각합니다..

**Comment by mrchypark** [comment]
@loveactualry 트랙에 대해서도 예시로 작성한 겁니다. 논의가 필요합니다.
발표자는 언제든 수정 보완하여 재 제출 가능한 것으로 생각했습니다. 논의가 필요합니다.
지원 부분도 논의해야 할 부분으로 보입니다.
필요한 부분임에 공감합니다.

말씀드린 것 처럼 디테일 모두가 새로운 논의거리입니다.

제가 제안한 방식에서 토론했으면 하는 범위는
1. 발표를 사전 녹화방식으로 진행
1. 발표자를 사전 선정하지 않고 사후 검수만 진행
1. 검수에 조건을 최소한으로만 진행

정도 인거 같습니다.

**Comment by loveactualry** [comment]
네네.. 적고 나서 해당 이슈와는 좀 거리가 있다고 느끼긴 했습니다. 정리 감사합니다 ㅎㅎ
1. 라이브 방식 보다는 사전 녹화 후, 스케줄에 따라 순차 방송하는게 나아보입니다. 실시간은 방송 오류 등 다양한 돌발 상황 발생 가능성이 크다는 생각이 듭니다.
2. 발표자 사전 선정하지 않는다는게 어떤 의미인지 설명 부탁드려도 될까요?
3. 최소한의 기준만 만족한다면 pass 하는 방향으로 진행하는게 괜찮을 것 같습니다.

**Comment by mrchypark** [comment]
@loveactualry 최소한의 기준만 만족하면 pass 하는 방향과 같은 맥락입니다.

기존 컨퍼런스의 발표자 모집은 

1. 발표자의 제목과 초록 혹은 발표 자료에 의한 신청
1. 컨퍼런스 운영에서 심사 후 사전 선정
1. 발표자의 준비
1. 실제 발표

로 이루어 집니다.

이때, 실제 발표를 보고 선정하거나 할 수 없기 때문에 여러가지 조건으로 발표자를 사전에 심사 해서 선정한 후,
발표 준비를 맡기게 됩니다.

영상에 대해 최소한의 기준만 만족한다면 패스하자는 방식을 제가 사후 검수로 표현하였습니다.

**Comment by KeunhoLee** [comment]
- @loveactualry 님과 같은 이유로 사전녹화방식에 찬성합니다. 

- @mrchypark 님이 제안하신 방식에서
1. 마감일을 몇차례 지정해놓고 그전까지 업로드 된 영상은 모두 동일한 시점에 업로드 된 것으로 간주하는 방식은 어떨까요? 
  --> 스케쥴 선점이 영상 업로드 시점에 너무 의존하지 않았으면 좋겠습니다.

2. 스케쥴 선점시 희망 스케쥴을 몇지망까지 받는건 어떨까요? 
  --> 동일 스케쥴에 다수의 발표자가 pass한 경우를 위해 필요할 것 같습니다.

3. 검수 체크리스트에 트랙 주제와 부합하는 지를 측정할 수 있는 항목이 추가 되었으면 합니다.

**Comment by mrchypark** [comment]
트랙 구성에 대한 논의는 https://github.com/R-Korea/RUCK2020/issues/20 에서 진행하겠습니다.

**Comment by mrchypark** [comment]
@KeunhoLee 생각해봐야 할 포인트네요! 의견 제안해주셔서 감사합니다.
저는 스케쥴 선점이 빨리 업로드 해야 하는 동인이 될거라 생각해서 방법을 설계하였습니다.
몇차례의 마감을 통해 목표일을 동기 부여할 수 있겠네요.

예를 들어 40분 영상은 언제까지, 20분 영상은 언제까지 같이 차등을 두는 것이 방법일 수 있겠습니다.

**Comment by mrchypark** [comment]
스케줄 선점에 대해서도 논의를 https://github.com/R-Korea/RUCK2020/issues/21 에서 진행하겠습니다.

**Comment by mrchypark** [comment]
본 이슈는 발표 방식 / 발표자 모집 방법으로 나누고 종료합니다.
