### ISSUE TITLE
RUCK2020 로고

### ISSUE THREAD

**Issue by mrchypark** [R-Korea/RUCK2020#18]
행사를 대표하는 로고가 필요합니다.

"참여와 발굴" 이라는 주제+R 언어 를 표현할 수 있는 디자인 컨셉을 제안해주세요.

누군가 나서주시지 않는다면, 흑.

추천도, 소식 공유도 정말 감사드립니다. 아니면 여기에 바로 결과물을 공유해주세요!

**Comment by encaion** [comment]
흠... 2020년이고, R 4.0.0 버전이 나온 해라서 이걸 같이 조합하면 참 좋을듯 해요.

**Comment by mrchypark** [comment]
@encaion 4 버전 도 좋은 접근이네요. 의견 감사드립니다!

**Comment by mrchypark** [comment]
어느 분을 추천해주셔도, 소식을 공유해주셔도 정말 감사하겠습니다.

**Comment by YoungjunNa** [comment]
아이고.. 고생이 많으십니다. 커뮤니티 발전을 위해 힘써 주셔서 고맙습니다😊

**Comment by mrchypark** [comment]
@YoungjunNa 아닙니다. ㅎㅎ 이렇게 응원해주셔서 대단히 감사드립니다.

다른 기여 방식으로 @YoungjunNa  님께서도 참여해주실 거라 기대해도 괜찮을까요?ㅎㅎ

**Comment by YoungjunNa** [comment]
아이고 ㅋㅋ 제가 얼마나 도움이 되련지 모르겠네요.. 필요한 것 있으면 페이스북 메신져 주세요! 손 닿는 한 돕겠습니다.

**Comment by mrchypark** [comment]
https://www.loud.kr/ 

이 사이트 이용해서 로고 의뢰 후 후원자의 결제로 진행 예정

**Comment by mrchypark** [comment]
![image](https://user-images.githubusercontent.com/6179259/98367848-abc6db80-2079-11eb-83c8-534d3fcdcda4.png)


vat 별도라고 하니 조금더 가격을 확인해 보겠습니다.

**Comment by loveactualry** [comment]
기간이나 일정은 어느정도로 걸릴까요?! 시간이 걸릴 것 같은 느낌도 들어서요!

**Comment by YoungjunNa** [comment]
후원이라고 하기엔 부끄럽네요..ㅎㅎ 찬조.. 정도로 하시죠. 
참여하시는 귀한 인력분들 바쁜 시간 내주셔서 회의하고 기획해 주셔서 고맙습니다.

**Comment by mrchypark** [comment]
@YoungjunNa 죄송하게도 이번 후원을 저의 준비 부족으로 받기 어렵게 되었습니다. 죄송합니다.

**Comment by mrchypark** [comment]
![ruck2020-logo](https://user-images.githubusercontent.com/6179259/102016464-86c63680-3da4-11eb-9bbb-7f8a3f7171f6.png)
