### ISSUE TITLE
트랙 설계

### ISSUE THREAD

**Issue by mrchypark** [R-Korea/RUCK2020#20]
발표 트랙에 대한 아이디어 논의 공간 입니다.

우선 전통적인 3~5 트랙과 순서대로 송출하기 라는 방식이 있습니다. 각 트랙에 테마를 잡아서 진행하기도 합니다.

개인적으로 오프라인의 방법을 그대로 사용하는 방식이라 선호하지 않습니다만, 온라인에 어울리는 방식을 아직 찾지 못하였습니다.

**Comment by jhgil92** [comment]
트랙 설계와 발표자 섭외 중 무엇이 먼저 이루어져야 되는지 조금 헷갈리네요.
개인적인 생각으로는 발표자 섭외가 어느정도 윤곽(ex, 발표 프로그램 개수)이 잡혀야 효율적인 트랙 설계가 가능할 듯 싶습니다.

몇 분의 발표자가 현실적으로 섭외 가능한 지 대략 생각하는 범위가 있으실까요??

#### 과거 RUCK 프로그램 갯수 (참고용)
| 연도 | 프로그램 갯수 | 링크 |
|------|-----------------|------|
| 2016 | 7 | https://ruck2016.r-kor.org/ |
| 2017 | 11 | https://ruck2017.r-kor.org/ |
| 2018 | 15 | https://ruck2018.r-kor.org/program/ |
| 2019 | 10 | https://ruck2019.r-kor.org/program/ |

**Comment by mrchypark** [comment]
@jhgil92 보통은 트랙을 설계한 후 거기에 맞게 발표자가 지원하는 형태를 띄는 것으로 알고 있습니다.

물론 자유로 신청하게 하고, 트랙을 배정하는 방법도 진행했던거 같구요.


말씀드린 것 처럼, 트랙은 오프라인의 물리적인 제약에서 가능한 설계인데요.
온라인으로 전환된 만큼 최대한 온라인의 장점을 활용할 수 있는 방향이면 좋겠다고 생각하고 있습니다.

이게 고민이기만 해서 스트레스네요. 어떤게 좋은 설계인지 잘 모르겠습니다.

일정 시간 고민해보고 안되면 트랙을 지정하던지, 발표내용을 보고 맞추던지 하면 좋을 것 같습니다.

**Comment by loveactualry** [comment]
개인적인 선호도는 온라인인 경우 트랙보다는 순차 송출 방식이 편했던 것 같습니다.
참여했던 컨퍼런스는 주로 평일 업무 시간에 진행되던 터라 업무(?)중에 같이 들어 한 영상을 꾸준히 들었던 경우가 한두번 있었습니다.

오프라인에서 느꼈던 골라듣는 재미가 온라인에서 반영될 수 있다면 트랙 방식도 좋은 방향이라 생각합니다.

우선은 개인적인 경험을 적어 보았고 저도 고민 하고 추가적으로 의견 나누도록 하겠습니다!

**Comment by mrchypark** [comment]
트랙을 유튜브의 플레이 리스트로 생각할 수도 있습니다.

라이브 송출이 아니라 일정 시점에서 각 플레이리스트 전체 공개 하는 방식이 가능합니다.

혹은 사전 행사로 모든 발표 리스트와 제목을 공유하고, 사람들에게 "플레이 리스트를 만들어서 공유해주세요" 도 가능할 것 같습니다.

**Comment by KeunhoLee** [comment]
오프라인 컨퍼런스를 온라인으로 옮긴다는 개념 보다는, 온라인이라는 플랫폼의 특성을 잘 활용할 수 있는 방식으로 새롭게 시도해보는 것도  괜찮을 것 같습니다.

**Comment by mrchypark** [comment]
우선 빨리 트랙 설계를 의사결정해야 해서, 우선 미팅때 나온 가안을 공유합니다.

1. 학계
1. 산업계 - 분석가
1. 산업계 - 분석가외 모두
1. 자유

다른 분들 의견 주시면 감사하겠습니다.

**Comment by mrchypark** [comment]
특별히 발표에 "번역" 장르를 권장하는 것을 제안합니다. 한국에서 생산하는 많은 컨텐츠가 번역임에도 불구하고 그 가치를 인정받지 못하거나, 과거에는 그것을 자신의 것으로 왜곡하는 경우가 많았습니다.

자신의 것으로 왜곡하는 경우는, 번역이 빠르게 컨텐츠를 생산하기 좋은 방법이면서, 다른 사람들에 비해 접근성이 좋은 경우 이익을 취하기 쉽기 때문입니다. 하지만 세상이 많이 변해서 많은 사람들이 번역했지만, 자신의 것처럼 작성한 것을 발견하기는 매우 쉬워졌습니다. 

이 문제에서 역시 빠르게 컨텐츠를 생산하기에 좋은 방식이라는 점은 부정하기 어렵습니다. 번역 그 자체가 가지는 정보 전달 중간자로써의 역할과 가치도 중요하다고 생각합니다. 그렇기에 원작자를 존중하는 방식으로 번역이 진행되는 것은 한국어 컨텐츠를 생산하는 좋은 방식이라고 생각합니다.

**Comment by mrchypark** [comment]
시간에 대한 의견 받습니다.

개인적으로는 20분이 적당하지 않나 생각하고 있습니다만, 감각적인 영역이라 논의하면 좋겠습니다.

**Comment by youngwoos** [comment]
> 우선 빨리 트랙 설계를 의사결정해야 해서, 우선 미팅때 나온 가안을 공유합니다.
> 
> 1. 학계
> 2. 산업계 - 분석가
> 3. 산업계 - 분석가외 모두
> 4. 자유
> 
> 다른 분들 의견 주시면 감사하겠습니다.

학계/산업계의 범위가 커서 특징이 분명하게 다른 분야가 한데 묶이는 문제가 있지 않을까요?
예를 들어 '학계'에 경영학, 의학, 생물학 등이 묶이고 '산업계'에 조사업, IT 서비스업, 교육업 등이 묶일 수 있을텐데요, 이러면 주제가 너무 달라 범주의 역할이 모호하지 않을까 합니다.

그보다는 분석 방법론 단위로 나누면 어떨까요? 예를 들면
1. 예측 분석
2. 탐색적 분석
3. 배포(또는 데이터 파이프라인 운용)

**Comment by rhyeu** [comment]
> > 우선 빨리 트랙 설계를 의사결정해야 해서, 우선 미팅때 나온 가안을 공유합니다.
> > 
> > 1. 학계
> > 2. 산업계 - 분석가
> > 3. 산업계 - 분석가외 모두
> > 4. 자유
> > 
> > 다른 분들 의견 주시면 감사하겠습니다.
> 
> 학계/산업계의 범위가 커서 특징이 분명하게 다른 분야가 한데 묶이는 문제가 있지 않을까요?
> 예를 들어 '학계'에 경영학, 의학, 생물학 등이 묶이고 '산업계'에 조사업, IT 서비스업, 교육업 등이 묶일 수 있을텐데요, 이러면 주제가 너무 달라 범주의 역할이 모호하지 않을까 합니다.
> 
> 그보다는 분석 방법론 단위로 나누면 어떨까요? 예를 들면
> 
> 1. 예측 분석
> 2. 탐색적 분석
> 3. 배포(또는 데이터 파이프라인 운용)

- 학계 ->이론 (Theory)
- 시각화 방법(Visualization)
- 도메인 중시(Data Domain)
- 엔지니어링(Data Engineering) 
- R help 문서 및 튜토리얼 번역, 소개

등으로 정리하면 어떨까요?

**Comment by mrchypark** [comment]
기여 받은 발표들을 보고 정하는 걸로 하겠습니다.
