### ISSUE TITLE
발표자의 영상 제출 방식

### ISSUE THREAD

**Issue by mrchypark** [R-Korea/RUCK2020#21]
발표자의 영상을 제출 받는 데 있어 방식을 논의하는 공간입니다.

현재까지 아래 방법이 제안되었습니다.

1. 선착순
1. 몇차례의 마감일

트랙 구성과 맞물려 논의되어야 하는 내용이긴 합니다만, 큰 틀에서 이야기 되었으면 합니다.

**Comment by loveactualry** [comment]
1~n차 마감일을 두면서 차수 별 선착순 혼합 방식이 어떨까 생각해봅니다.

#17 에 이어서 스케쥴 논의는 차수 별 제출순으로 송출 시간 선택권을 주는 것도 어떨까 하는 의견 제시합니다.

**Comment by mrchypark** [comment]
@loveactualry 같은 차수내의 선택권은 어떻게 하는게 좋을까요?

**Comment by loveactualry** [comment]
@mrchypark 
1. 차수 내 영상 우선 제출 하신 분에게 먼저 선택권 주는 방식  
2. 동일 차수 내 발표자 송출 시간 선착순 선택 방식(ex: 수강신청)

이 있을 것 같습니다.

운영진 편의 측면에서는 2번 방식이 편하지 않을까 생각해봅니다.

**Comment by mrchypark** [comment]
https://github.com/R-Korea/RUCK2020/issues/17 본 이슈가 발표자 모집 방법인 것으로 하겠습니다.

**Comment by youngwoos** [comment]
동시 송출 여부가 먼저 결정되어야 논의할 수 있을듯 합니다.
