### ISSUE TITLE
정기 미팅 일정 논의

### ISSUE THREAD

**Issue by mrchypark** [R-Korea/RUCK2020#22]
주 2회 각 60분으로 결정됨에 따라

요일과 시간을 정하도록 하겠습니다.

**Comment by mrchypark** [comment]
화, 금 10시를 제안합니다.

**Comment by jhgil92** [comment]
해당 안건의 종결을 제안합니다!

**Comment by mrchypark** [comment]
넵 화금 10시에 한시간으로 진행하겠습니다.

@jhgil92 감사합니다. 👍
