### ISSUE TITLE
영상 촬영을 위한 ppt 템플릿 + 배경 템플릿 제작

### ISSUE THREAD

**Issue by mrchypark** [R-Korea/RUCK2020#30]
발표자분들이 발표자료를 제작할 때 사용할 ppt 템플릿과

얼굴 영상을 함께 사용한다면 사용할 배영 템플릿이 필요합니다.

아직 로고도 나오지 않은 상황이라 로고와 함께 일관성 있게 제작되면 좋을 것 같습니다.

ppt의 경우 키노트도 함께 고려할 수 있으면 좋겠다고 생각하고 있습니다.

**Comment by mrchypark** [comment]
배경 템플릿 예시

http://www.bloter.net/archives/463210

**Comment by jhgil92** [comment]
if kakao 2019 예시

https://if.kakao.com/2019/program

**Comment by mrchypark** [comment]
로고 제작시 포스터 까지 진행할 예정인데, 그 디자인 시안에서 발췌해서 사용하는 것으로 제안함

**Comment by mrchypark** [comment]
![slide_template](https://user-images.githubusercontent.com/6179259/102016218-2a164c00-3da3-11eb-9a72-4768f2d7e3d8.png)
