### ISSUE TITLE
스튜디오 후원

### ISSUE THREAD

**Issue by mrchypark** [R-Korea/RUCK2020#31]
제 예상보다 직접 촬영에 대해 허들이 높을 수 도 있겠다는 판단을 하게되었습니다.

스튜디오 후원 논의를 새로 오픈하겠습니다.

_Originally posted by @mrchypark in https://github.com/R-Korea/RUCK2020/issue_comments/708189698_

**Comment by mrchypark** [comment]
스튜디오의 직접 후원을 요청해야 발표영상을 확보할 수 있겠다는 생각이 들었습니다. 운영위 의견이 궁금합니다.

스튜디오의 직접 후원을 요청하는 이유는 발표 지원자중 생각보다 많은 사람이 영상 제작 허들을 느낄 것이다는 것을 느꼈기 때문에, 더 많은 분들에게의 지원이 필요할 수 있겠다고 생각했기 때문입니다.

**Comment by loveactualry** [comment]
직접 후원을 받게 되면 장비나 공간 활용을 좀 더 유연하게 활용할 수 있을까요..? 비교적 시간 여유를 가지고 진행할 수 있다던지요..

**Comment by youngwoos** [comment]
단팟스튜디오 사당점
https://danpod.modoo.at/

영상 촬영 가능한 스튜디오 대관료가 1시간에 20,000원 입니다.
https://danpod.modoo.at/?link=8qqe60vz

촬영시 영상 녹화 가능한 SD카드를 지참해야 합니다.

**Comment by mrchypark** [comment]
@loveactualry 운영위 리소스가 되는 한 가능하지 않을까 싶습니다. 물론 가능성을 타진하기 위해 연락해봐야 경계선을 확인할 수 있을 것 같아요.

**Comment by youngwoos** [comment]
미디어자몽
https://zamong.co.kr/studio/reservation

**Comment by mrchypark** [comment]
이노베이션 아카데미 와 논의가 된 부분이 있는거 같아서 컨택 중

**Comment by mrchypark** [comment]
16일(금) 정기 미팅에서 이노베이션 아카데미 관련 내용 공유하겠습니다.

기본적으로 신청만 하면 사용가능한 좋은 장비의 스튜디오를 공유받아 사용할 수 있다고 설명들었습니다.

**Comment by mrchypark** [comment]
일정 논의 후 신청하겠습니다.
