### ISSUE TITLE
발표 시간 제한

### ISSUE THREAD

**Issue by youngwoos** [R-Korea/RUCK2020#32]
만약 라이브로 순차 송출하지 않고 플레이리스트 방식으로 하게 된다면 발표 시간에 제한을 두지 않으면 어떨까요?

발표 시간이 아주 길거나 아주 짧아도 괜찮다고 생각합니다. 내용에 따라 효과적인 길이가 다를 수 있으니까요.

가급적 20분 내외로 하도록 제안하고, 5분 내외로 짧거나 40분 내외로 길어도 괜찮다고 안내하면 어떨까 합니다.

**Comment by mrchypark** [comment]
발표 시간은 20분으로 추천하되 제한하지 않는 것으로 하겠습니다.
