### ISSUE TITLE
스튜디오 촬영 도움을 위한 지원자

### ISSUE THREAD

**Issue by mrchypark** [R-Korea/RUCK2020#33]
이노베이션 아카데미에서 촬영을 진행하기 위한 현장 도움이 필요합니다.

사전 장소 방문 이후 어떤 역할을 수행해야 하는지 확인하고,
그 부분 도움을 요청해야 할 것으로 판단하였습니다.

**Comment by youngwoos** [comment]
촬영 일정이 먼저 정해져야 판단할 수 있지 않을까요?

**Comment by youngwoos** [comment]
> 이노베이션 아카데미에서 촬영을 진행하기 위한 현장 도움이 필요합니다.
> 
> 사전 장소 방문 이후 어떤 역할을 수행해야 하는지 확인하고,
> 그 부분 도움을 요청해야 할 것으로 판단하였습니다.

촬영 일정이 먼저 정해져야 판단할 수 있을듯합니다.

**Comment by mrchypark** [comment]
코로나 단계 격상으로 취소
