### ISSUE TITLE
커뮤니티 소통 방식

### ISSUE THREAD

**Issue by mrchypark** [R-Korea/RUCK2020#35]
16일 미팅에서 논의한 방식으로

1. R-korea 의 페이지에 소통용 포스트를 작성
1. 그 포스트를 운영위 등에서 공유하는

방식으로 공지를 하기를 안효준님의 문제 제기를 통해 결정하였습니다.

**Comment by loveactualry** [comment]
운영진에게 페이지 작성 권한 부여
게시물 작성 후 공유 방식
