### ISSUE TITLE
컨퍼런스 관련 공지 (~23일 까지)

### ISSUE THREAD

**Issue by loveactualry** [R-Korea/RUCK2020#38]
목차와 초안 적어보았습니다.
영상 제출 이전에 앞서 초록 지원에 대한 공지를 작성해야 했다는 생각이 듭니다....ㅠㅠㅠㅠ
다 적고 나니 생각이 들었네요.
수정사항과 작성 방향 코멘트 주시면 반영해서 수정하도록 하겠습니다.

---------------------------------------------------------------------

포함 내용
- 발표자 모집
- 트랙(주제)
- 영상 제출(방식 ,길이 등등)
- 발표자 지원 방안(대략적)
- 

안녕하세요, <커뮤니티, 단체>.
RUCK 2020이 RUCK 역사상 처음으로 11월 28일 온라인으로 진행됩니다.
참여와 발굴의 비전을 갖고 다양한 분야에서 많은 분을 모시고 컨퍼런스를 진행하고자 합니다.

RUCK는 여러분의 참여로  이루어 지고 있습니다.
온라인으로 빛내주실 발표자를 찾고 있습니다!
발표는 온라인으로 진행되는 만큼 영상으로 진행됩니다.
영상 제작이 낯선 발표자 분들을 위해 커뮤니티에서 도움도 드리니 부담 내려 놓고 지원 부탁드립니다!

트랙(주제)
1. 트랙
2. 트랙

발표 일정
영상 제출 마감일
영상 촬영 지원 일정

카카오톡 오픈 채팅방에서 지원 혹은 추천 부탁드립니다.

오픈 채팅방

https://open.kakao.com/o/ggWBTzBc

**Comment by rhyeu** [comment]
- 역사와 모임의 목적 부분이 추가되면 어떨까 싶습니다.
처음 도입부에 (2015년부터 R생태계 활성화와 R사용자 교류를 위해 이루어졌던) RUCK 2020이 RUCK 역사상 처음으로 11월 28일 온라인으로 진행됩니다.

**Comment by loveactualry** [comment]
RUCK2020 종료로 이슈 클로징합니다.
