### ISSUE TITLE
행사 일정 조정

### ISSUE THREAD

**Issue by mrchypark** [R-Korea/RUCK2020#42]
현재 준비 상황과 해커톤 일정과 관련하여 12월 초 혹은 중으로 일정을 조율하면 어떨까요? (/w 길지홍님)

**Comment by mrchypark** [comment]
변경 가능한 후보일을 12월 19일(토) 입니다.

**Comment by mrchypark** [comment]
반대가 없어서 변경을 확정합니다.

**Comment by loveactualry** [comment]
시간 논의도 필요할 것 같습니다!
