### ISSUE TITLE
useR! 2020 결과물 벤치 마킹 의견

### ISSUE THREAD

**Issue by mrchypark** [R-Korea/RUCK2020#49]
전체적으로 3가지 프로그램으로 진행

1. 키노트
2. 튜토리얼
3. 기여받은 세션

키노트는 아는 대로,
튜토리얼은 라이브로 진행한 듯. 누구가 어떤 내용으로 얼마나 진행함, 몇시에 진행함을 공지
튜토리얼 세션의 장점이라면 화상 솔루션으로 개별 진행자가 진행하고, 녹화는 자유로 맡기는 형태가 되는 듯.

기여받은 세션(contributed sessions)은 5분내, 10분내, 15분내 로 구분하여 사람들에게 사전 녹화된 영상을 기여받은 형태로 보임

기여받은 세션이 아마 (제가) 상상하던 컨퍼런스의 설계로 보임.

키노트를 할꺼라면 섭외문제
튜토리얼 또한 섭외문제가 있음. 하지만 튜토리얼이 실시간으로 진행되는 만큼 기존의 컨퍼런스에서 기대하는 이익을 얻을 가능성이 있음

useR! 이라는 특성상 발표의 중심이 튜토리얼로 보이기도 해서, 라이브 세션 이라고 하고, 튜토리얼도 감사하다 형태가 어떨까 싶음

**Comment by mrchypark** [comment]
https://user2020.r-project.org/

**Comment by loveactualry** [comment]
고생하셨습니다! ㅠㅠ 기여 세션은 녹화 영상과 발표 자료가 지금도 서비스가 되고 있네요!

그 중 웹 어플리케이션에서 샤이니가 절반 이상을 차지하네요.

저도 운영위 참여하면서 생각해오던거지만 저희(?)가 생각하던 컨퍼런스 설계가 아닐까 생각해봅니다!

**Comment by loveactualry** [comment]
튜토리얼은 hands-on 느낌으로 생각해도 괜찮으려나요..?

**Comment by mrchypark** [comment]
@loveactualry 기여 세션은 자유롭게 지원받고, 튜토리얼을 라이브로 하는 설계가 유의미해 보여요

hands-on 인줄 알았건만, 발표만 진행하신 분들도 있는거 같아요.ㅎㅎ
