### ISSUE TITLE
기여 세션의 규격 제안

### ISSUE THREAD

**Issue by mrchypark** [R-Korea/RUCK2020#50]
총 5단계로 규격을 안내하고, 자유롭게 보내주세요.

1. 슬라이드만(그 자체만으로 내용이 이해가 되면 좋겠음)
1. 5분 미만
1. 10분 미만
1. 20분 미만
1. 무제한

이름은 조금 수정해야 겠습니다만, 이렇게 제안되었습니다.

**Comment by loveactualry** [comment]
1. 슬라이드에 대한 가이드(?)로는 적어주신 '내용 이해가 되었으면 좋겠음'과 R 사용정도로 하면 괜찮겠죠?

**Comment by mrchypark** [comment]
제작 가이드라고 크게 정의하고, 계속 업데이트 하면 어떨까요?

@loveactualry 그 정도면 좋지 않을까 싶습니다. 내용이 이해가 되었으면 좋겠음은 뭔가 가이드에 맞게 문구를 좀 수정하면 좋겠는데, 좋은 아이디어가 떠오르지 않네요 ㅠ

**Comment by loveactualry** [comment]
> 제작 가이드라고 크게 정의하고, 계속 업데이트 하면 어떨까요?
> 
> @loveactualry 그 정도면 좋지 않을까 싶습니다. 내용이 이해가 되었으면 좋겠음은 뭔가 가이드에 맞게 문구를 좀 수정하면 좋겠는데, 좋은 아이디어가 떠오르지 않네요 ㅠ

그러게요.. 참여하시는 분들의 수준도 천차만별 일 것 같아 이해의 기준이 다 다를 수 있겠네요.
저번에 나눴던 내용들 중 '강의 주제와 슬라이드 내용 부합 여부'는 어떨까 합니다. 주제랑 슬라이드 내용이 맞는다면 어느정도 이해도 되지 않을까 하는 생각이 드네요. 지나치게 수식이 많거나 코드 위주면 다르게 생각할 수 있으려나요..? ㅠ

**Comment by mrchypark** [comment]
1. 슬라이드만(블로그 포스트 포함) > 블로그 라면 첨부할 문구나, 배너가 필요함
2. 영상(~5분, ~10분, ~20분, 이상) 

으로 확정
