### ISSUE TITLE
컨퍼런스 내용 관련 설문조사(1120~)

### ISSUE THREAD

**Issue by loveactualry** [R-Korea/RUCK2020#51]
페이지 게시물 링크(PREVIEW 형식)

https://www.facebook.com/r.korea/posts/1255119681519392

페이지 주소
https://www.facebook.com/r.korea

**Comment by loveactualry** [comment]
페이스북 그룹 게시 현황(20201120) 
굵은 글씨 게시한 곳

R 사용자 다수 커뮤니티
**데이터분석커뮤니티 https://www.facebook.com/groups/datacommunity/**
**Korea Shiny User Group https://www.facebook.com/groups/1934593613301733/
Tidyverse Korea https://www.facebook.com/groups/tidyverse/**

데이터 분석 스터디 그룹 관련
**통계마당 https://www.facebook.com/groups/632755063474501/**
**통계분석연구회 https://www.facebook.com/groups/statsas**
싸이그래머 https://www.facebook.com/groups/psygrammer/
**데이터 피플 코리아 커뮤니티 https://www.facebook.com/groups/datapeoplekorea/**
**데이터뽀개기 https://www.facebook.com/groups/databreak/**

데이터 일반
**데이터저널리즘 코리아 https://www.facebook.com/groups/DataJournalismKR/**
**빅데이터&스몰데이터 https://www.facebook.com/groups/BigdataSmalldata/**
데이터 시각화의 모든 것 https://www.facebook.com/groups/datainsouthkorea/
생활데이터 https://www.facebook.com/groups/livingdata/
**데이터로 세상읽기 https://www.facebook.com/groups/321822011200479/**

머신러닝 관련
생활코딩 https://www.facebook.com/groups/codingeverybody/
**AI Korea https://www.facebook.com/groups/AIKoreaOpen/?multi_permalinks=3618725808161503**
**캐글 코리아 https://www.facebook.com/groups/KaggleKoreaOpenGroup/**
**TensorFlow KR https://www.facebook.com/groups/TensorFlowKR/**
한국 인공지능 커뮤니티 https://www.facebook.com/groups/dev4startup/
모두의연구소 커뮤니티 https://www.facebook.com/groups/modulabs/
**한국데이터사이언스학회 https://www.facebook.com/groups/datasci/**

카카오톡 오픈채팅방
R Dev team https://open.kakao.com/o/gEdB6wo
Python R 입문하신 분들 정보공유해요 https://open.kakao.com/o/g1hE9tl
데이터 수다방 데분깜냥 https://open.kakao.com/o/gwAbO2W
데이터분석과 기계학습 https://open.kakao.com/o/gHY6rPp
데이터분석 QnA&네트워킹 https://open.kakao.com/o/gcaPzHr(중복)
Python Data Science https://open.kakao.com/o/gjbt5qn
케라스 코리아 오픈채팅 https://open.kakao.com/o/g93MSBV

**Comment by loveactualry** [comment]
설문 링크
https://forms.gle/4nRHmw5rUpQRrdcv6

설문 결과 링크
https://docs.google.com/spreadsheets/d/1jZudK8uZyzi4dE5bw0PAcuLcR2Ouis-mUzMw_LOJO68/edit?usp=sharing

**Comment by loveactualry** [comment]
컨퍼런스 종료 후, R-korea로 결과물 자산화 예정.

**Comment by rhyeu** [comment]
> 페이스북 그룹 게시 현황(20201120)
> 굵은 글씨 게시한 곳
> 
> R 사용자 다수 커뮤니티
> **데이터분석커뮤니티 https://www.facebook.com/groups/datacommunity/**
> **Korea Shiny User Group https://www.facebook.com/groups/1934593613301733/**
> 
> 데이터 분석 스터디 그룹 관련
> **통계마당 https://www.facebook.com/groups/632755063474501/**
> **통계분석연구회 https://www.facebook.com/groups/statsas**
> 싸이그래머 https://www.facebook.com/groups/psygrammer/
> **데이터 피플 코리아 커뮤니티 https://www.facebook.com/groups/datapeoplekorea/**
> **데이터뽀개기 https://www.facebook.com/groups/databreak/**
> 
> 데이터 일반
> **데이터저널리즘 코리아 https://www.facebook.com/groups/DataJournalismKR/**
> **빅데이터&스몰데이터 https://www.facebook.com/groups/BigdataSmalldata/**
> **데이터 시각화의 모든 것 https://www.facebook.com/groups/datainsouthkorea/**
> **생활데이터 https://www.facebook.com/groups/livingdata/**
> **데이터로 세상읽기 https://www.facebook.com/groups/321822011200479/**
> 
> 머신러닝 관련
> 생활코딩 https://www.facebook.com/groups/codingeverybody/
> **AI Korea https://www.facebook.com/groups/AIKoreaOpen/?multi_permalinks=3618725808161503**
> **캐글 코리아 https://www.facebook.com/groups/KaggleKoreaOpenGroup/**
> **TensorFlow KR https://www.facebook.com/groups/TensorFlowKR/**
> 한국 인공지능 커뮤니티 https://www.facebook.com/groups/dev4startup/
> 모두의연구소 커뮤니티 https://www.facebook.com/groups/modulabs/
> **한국데이터사이언스학회 https://www.facebook.com/groups/datasci/**
> 
> 카카오톡 오픈채팅방
> R Dev team https://open.kakao.com/o/gEdB6wo
> Python R 입문하신 분들 정보공유해요 https://open.kakao.com/o/g1hE9tl
> 데이터 수다방 데분깜냥 https://open.kakao.com/o/gwAbO2W
> 데이터분석과 기계학습 https://open.kakao.com/o/gHY6rPp
> 데이터분석 QnA&네트워킹 [https://open.kakao.com/o/gcaPzHr(중복)](https://open.kakao.com/o/gcaPzHr(%EC%A4%91%EB%B3%B5))
> Python Data Science https://open.kakao.com/o/gjbt5qn
> 케라스 코리아 오픈채팅 https://open.kakao.com/o/g93MSBV



> 페이스북 그룹 게시 현황(20201120)
> 굵은 글씨 게시한 곳
> 
> R 사용자 다수 커뮤니티
> **데이터분석커뮤니티 https://www.facebook.com/groups/datacommunity/**
> **Korea Shiny User Group https://www.facebook.com/groups/1934593613301733/
> 
> 데이터 분석 스터디 그룹 관련
> **통계마당 https://www.facebook.com/groups/632755063474501/**
> **통계분석연구회 https://www.facebook.com/groups/statsas**
> 싸이그래머 https://www.facebook.com/groups/psygrammer/
> **데이터 피플 코리아 커뮤니티 https://www.facebook.com/groups/datapeoplekorea/**
> **데이터뽀개기 https://www.facebook.com/groups/databreak/**
> 
> 데이터 일반
> **데이터저널리즘 코리아 https://www.facebook.com/groups/DataJournalismKR/**
> **빅데이터&스몰데이터 https://www.facebook.com/groups/BigdataSmalldata/**
> 데이터 시각화의 모든 것 https://www.facebook.com/groups/datainsouthkorea/
> 생활데이터 https://www.facebook.com/groups/livingdata/
> **데이터로 세상읽기 https://www.facebook.com/groups/321822011200479/**
> 
> 머신러닝 관련
> 생활코딩 https://www.facebook.com/groups/codingeverybody/
> **AI Korea https://www.facebook.com/groups/AIKoreaOpen/?multi_permalinks=3618725808161503**
> **캐글 코리아 https://www.facebook.com/groups/KaggleKoreaOpenGroup/**
> **TensorFlow KR https://www.facebook.com/groups/TensorFlowKR/**
> 한국 인공지능 커뮤니티 https://www.facebook.com/groups/dev4startup/
> 모두의연구소 커뮤니티 https://www.facebook.com/groups/modulabs/
> **한국데이터사이언스학회 https://www.facebook.com/groups/datasci/**
> 
> 카카오톡 오픈채팅방
> R Dev team https://open.kakao.com/o/gEdB6wo
> Python R 입문하신 분들 정보공유해요 https://open.kakao.com/o/g1hE9tl
> 데이터 수다방 데분깜냥 https://open.kakao.com/o/gwAbO2W
> 데이터분석과 기계학습 https://open.kakao.com/o/gHY6rPp
> 데이터분석 QnA&네트워킹 [https://open.kakao.com/o/gcaPzHr(중복)](https://open.kakao.com/o/gcaPzHr(%EC%A4%91%EB%B3%B5))
> Python Data Science https://open.kakao.com/o/gjbt5qn
> 케라스 코리아 오픈채팅 https://open.kakao.com/o/g93MSBV

데이터 시각화의 모든 것, 생활데이터 페이지에 게시했습니다.

**Comment by loveactualry** [comment]
RUCK2020 종료로 이슈 클로징합니다.
