### ISSUE TITLE
발표 후보자들을 위한 단톡방 개설 제안

### ISSUE THREAD

**Issue by mrchypark** [R-Korea/RUCK2020#6]
현재 컨퍼런스 발표자분들을 모시기 위해서 독려활동을 해야 합니다.

그 방법에 있어 커뮤니티 참여자 분들을 초대하고, 그 분들에게 후보이신 분들을 초청 요청드려서 단톡방을 운영하는 것을 제안합니다.

이 단톡방의 참여 및 발표자 추천은 커뮤니티 기여에 해당합니다.

**Comment by loveactualry** [comment]
단톡방이라면 단체 카카오톡방을 의미하시는거죠?

**Comment by mrchypark** [comment]
@loveactualry  맞습니다. 다른 사용자 분들의 사용 편의성을 고려하면 카톡의 오픈채팅방이 가장 좋은 도구라고 생각합니다.

물론 api를 사용할 수 있는 다른 채널들 (ex> gitter, slack 등) 이 있습니다만, 참여를 높이기 위해서 많은 사람들이 익숙한 도구를 사용하는 것이 더 좋다고 판단해 제안했습니다.

**Comment by mrchypark** [comment]
전체 +1 확인해서 이슈 종료합니다.
