### ISSUE TITLE
운영위 구성에 대한 제안

### ISSUE THREAD

**Issue by mrchypark** [R-Korea/RUCK2020#7]
ruck2020은 현재 부족한 시간과 리소스 상황에 처해 있습니다.

이를 해소하는 방법으로 운영위 구성에서 후원은 제외하는 방법을 제안합니다.

후원은 풍성하고 성공적인 컨퍼런스를 진행하는데 있어 필수적인 요소임에는 분명합니다만, 현금 후원으로 인한 추가 리소스의 투입이 저는 필수적이라고 판단하고 있지 않습니다.

특히 온라인으로 전환되면서 많은 부분 비용 없이 가능한 부분이 있어 후원 조직 없이 운영위를 진행할 것은 제안합니다.

**Comment by youngwoos** [comment]
헌금 외에 상품 등의 후원은 가능할까요?

**Comment by mrchypark** [comment]
@youngwoos 제품의 후원은 추가적인 리소스 소모(회계처리 등) 없이 라면 가능할 것 같습니다. 

돈을 안받고 안쓰겠다가 목표라기 보다는, 돈을 받는 것 때문에 추가로 발생하는 일들을 같이 고려하면 하지 말자 였기 때문입니다.

**Comment by mrchypark** [comment]
금일 9시 까지 특별한 반대가 없는 한 위 제안으로 진행하겠습니다.

언제든지 @youngwoos 님 말씀처럼 현물 지원의 경우 이슈 열어주시면 논의 진행하면 좋을 것 같습니다.

**Comment by mrchypark** [comment]
RUCK 2020 은 현금 후원 없이 진행하겠습니다.
