### ISSUE TITLE
운영위 정기 미팅 일정 논의

### ISSUE THREAD

**Issue by mrchypark** [R-Korea/RUCK2020#9]
10월 5일 기준 딱 8주가 남은 시점에서, 정기 공개 미팅 일정을 정해야 되서 이슈 생성합니다.

논의 내용은 정기 미팅인 만큼

1. 주 몇 회로 할지
1. 무슨 요일에 할지
1. 몇시에 할지

입니다.

**Comment by mrchypark** [comment]
저는

주 2회
화요금 금요일
저녁 10시

를 제안합니다.

늦은 시간입니다만, 미국 등 다른 곳에서도 참여할 수 있는 시간이기 때문입니다.
횟수와 요일은 제 감각적인 판단이니, 다른 제안을 부탁드립니다.

요일의 경우 저는 월요일이 불가하고, 수요일이 간헐적으로 어려울 수 있습니다.

**Comment by KeunhoLee** [comment]
1. 중요사안에 대한 비정기 미팅을 별도 진행한다는 전제 하에 정기미팅은 주 1회가 어떨까 합니다.
2. 지난주중과 주말 진행된 내용을 정리하고 다음을 준비하기에는 주초인 월,화가 좋다고 생각합니다.
3. 첫 공개미팅 때 경험으로 미루어 보아 미팅시간을 90분 내외로 잡았을 때, 8~9시정도가 퇴근 이후 저녁식사나 개인용무 보고 부담스럽지 않게 진행할 수 있을 것 같습니다.

2번 문항이 1번에 따라오는 문항인 것 같은데, 1번을 우선적으로 논의한 뒤에 요일과 시간을 정하는 것은 어떨까요.
2,3번에 대한 의사결정 방법은 도구선정때와 동일하게 기한이 정해진 보팅방식으로 진행하는 것을 제안합니다.

**Comment by mrchypark** [comment]
@KeunhoLee 공감합니다. 특별히 다른 언급이 있지 않는한, 본 이슈는 주 횟수로 한정해서 진행하겠습니다.

**Comment by mrchypark** [comment]
정기 공개 온라인 미팅 의 성격이기 때문에, 주 1회시, 전체 정기 미팅 기회가 총 8회 남았습니다. 

저는 비정기 미팅을 고려하지 않고 주 2회를 제안했었는데, 비정기 긴급 미팅을 소집할 수 있다는 전제하에 주 1회에 찬성합니다.

**Comment by loveactualry** [comment]
정기 미팅은 주 1회로 하는게 어떨까 합니다.
비정기 미팅은 수시로 발생하지 않을까 하는 생각이 듭니다.

저는 요일은 큰 상관은 없으나 시간은 9시나 10시 정도가 어떨지 제안해봅니다.

**Comment by jhgil92** [comment]
주 2회 진행을 선호합니다.
그 이유는 비정기 미팅의 효율성에 대한 의문이 있기 때문입니다. (참여율, 효율성 등)
한정된 시간에 준비를 해야하기에 비정기 미팅을 피할수 없지만 최소화해야 한다고 생각합니다.

**Comment by mrchypark** [comment]
논의를 정리해보면 비정기 미팅의 여부에 따르겠네요. 비정기 미팅과 정기 미팅에 대한 각자의 인식을 공유하는게, 논의하는데 도움이 될 까 싶어 제 인식 먼저 공유합니다.

현재 운영위 미팅은 공개, 온라인을 지향하고 있습니다.  이 부분은 커뮤니티의 참여를 독려하는 부분과 아주 최소한의 PR을 함께 고려하고 있습니다. 또한 도구 사용법 공유(특히 github)가 부차적인 목표가 될 것 같습니다.

현재 토론과 논의가 깃헙 이슈로 진행되는 만큼, 온라인 정기 미팅은 그동안의 이슈를 정리하고, 빨리 의사결정해야 하는 것들을 바로 자리에서 결정하기 위한 자리로 생각하고 있습니다. 또한 글자로만 표현되지 않는 부분에 대해 표현하여 이슈로만 토론을 진행했을 때의 단점을 보완하기 위함입니다.

이 정기 미팅의 저의 인식에서 비정기 미팅은 제기된 이슈 중 의사 결정의 시급성이 공감대는 형성 했을 때 가능하다고 생각합니다. 물론 이때 채팅 도구의 의존도가 올라가는 단점이 있다고 생각합니다.

또 긴급 회의의 소집 요건도 중요한 요소가 될 것 같습니다. 채팅 도구에서 모두 동기적으로 호출되어 현재 이 이슈에 긴급성에 공감하고 바로 화상도구로 진행하는 것은 쉬운 일이 아닐 것이라 짐작합니다.

저도 재택근무를 하면서 화상 미팅은 수시로 진행합니다만, 일정 수 이상의 사람이 모이기 위해서는 3~5시간 이상의 버퍼를 두어야 하는 경험을 하였습니다. 물론 상황에 따라 빠르게 모임이 가능하기도 했습니다만, 이 부분은 업무 중인 상황을 고려했을때, 현재 운영위의 상황에 바로 대입하는 것은 어려울 것 같습니다.

정기 미팅을 주 2회, 1회에 90 분 정도로 예상하고, 주에 180분 할애하는 것은 쉬운 일이 아닙니다만. 각자의 사정에 상관없이 의사결정을 진행하고 운영위 운영이 계속되어야 함도 분명합니다.

**Comment by mrchypark** [comment]
위 인식에 더해 제 의견을 정리해보면, 주 2회를 선호하나 운영위 내에 긴급 소집에 대한 참여 의무에 대해 진지한 동의가 있다면 주 1회도 찬성합니다.

**Comment by mrchypark** [comment]
주1회 투표장

**Comment by mrchypark** [comment]
주2회 투표장

**Comment by KeunhoLee** [comment]
'비정기 미팅' 이라는 용어가 여러 의미로 쓰일 수 있는 것 같습니다.

@mrchypark 님께서 언급하셨던 '긴급소집'의 형태로 비정기 미팅이 열릴 수도 있겠지만 처음 제가 의도했던 바는 '짧은 간격으로 계획된 비정기 미팅' 이었습니다.

조금더 구체적으로 예를 들면 정기미팅의 마지막 아젠다로
- 논의된 건의 이행에대한 추가논의가 필요할 때
- 이행 중인 건의 진행상황을 다음 정기미팅 전에 확인할 필요가 있을 때
다음 정기미팅 이전에 비정기 미팅 일정을 가벼운 방식으로 결정하는 형태

정도를 생각하고 사용한 용어였습니다. 조금 더 구체적으로 적었어야 했네요.
제가 제안한 '중요사안에 대한 비정기 미팅을 별도 진행한다는 전제 하에 주 1회'라는 의견 생각하실 때
이부분 참고해주시면 감사하겠습니다.

추가로, @jhgil92 님 께서 우려하시는 바를 충분히 공감합니다.
한정된 시간에 준비를 해야하기 때문에 의견을 교환하는 자리는 많을수록 좋은 것 같습니다.

**Comment by youngwoos** [comment]
> 주2회 투표장

주 2회, 회당 60분 제안합니다.
시간 부담을 줄이면 참여도를 높일 수 있지 않을까 합니다.

**Comment by mrchypark** [comment]
제가 생각하는 미팅에서의 아젠다를 공유드리면 좋겠다고 생각합니다.

1. 이슈와 pr로 제기된 내용 중 아직 의사결정이 안된 부분들을 빠르게 의사결정합니다.
1. 의사결정이 완료된 내용 중 실행이 필요한 부분의 진행사항을 공유합니다.
1. 커뮤니티의 직접 참여에 의한 질답에 대응하고, 의견을 수렴합니다.

혹시 다른 용도를 더 생각하고 계신 것이 있으시면 공유 부탁드립니다.

**Comment by mrchypark** [comment]
제가 생각하는 미팅에서의 아젠다를 공유드리면 좋겠다고 생각합니다.

1. 이슈와 pr로 제기된 내용 중 아직 의사결정이 안된 부분들을 빠르게 의사결정합니다.
1. 의사결정이 완료된 내용 중 실행이 필요한 부분의 진행사항을 공유합니다.
1. 커뮤니티의 직접 참여에 의한 질답에 대응하고, 의견을 수렴합니다.

혹시 다른 용도를 더 생각하고 계신 것이 있으시면 공유 부탁드립니다.

**Comment by KeunhoLee** [comment]
> 제가 생각하는 미팅에서의 아젠다를 공유드리면 좋겠다고 생각합니다.
> 
> 1. 이슈와 pr로 제기된 내용 중 아직 의사결정이 안된 부분들을 빠르게 의사결정합니다.
> 2. 의사결정이 완료된 내용 중 실행이 필요한 부분의 진행사항을 공유합니다.
> 3. 커뮤니티의 직접 참여에 의한 질답에 대응하고, 의견을 수렴합니다.
> 
> 혹시 다른 용도를 더 생각하고 계신 것이 있으시면 공유 부탁드립니다.

3번 내용 중 '커뮤니티의 직접 참여' 에서 
'커뮤니티'에 해당하는 대상
'직접 참여'가 의미하는 바

두가지를 조금 더 자세히 설명 부탁드립니다.

**Comment by mrchypark** [comment]
@KeunhoLee 커뮤니티란 운영위 이외에 참여하는 모든 사람을 뜻합니다.

컨퍼런스에 관심있는 모두가 참여할 수 있다고 가정하고, 커뮤니티는 운영위를 제외한 모든 사람을 뜻합니다.

직접참여는 제가 단어를 좀 과장한 면이 있는 것 같습니다.
온라인 미팅을 개방해서 진행하는 만큼 커뮤니티 참여자의 행위를 뜻했습니다.
커뮤니티에서 온라인 미팅에 참여하여 구경을 하는 것도 참여이고, 질문이나 의견을 내는 것도 참여라고 생각합니다.

**Comment by mrchypark** [comment]
이 논의는 6일 21시에 종료됩니다.

**Comment by loveactualry** [comment]
결정에 따르겠습니다.

**Comment by mrchypark** [comment]
투표에 의해 주 2회 짧게!(60분 제한) 으로 결정하겠습니다.
